maraschneider/docref

app/models/approval.rb, app/models/approval_field.rb, app/models/clinic.rb, app/models/field.rb, app/models/specialty.rb, app/models/user_field.rb, app/models/user_specialty.rb, db/migrate/20191125144302_create_clinics.rb, db/migrate/20191125144721_add_columns_to_users.rb, db/migrate/20191125144935_create_specialties.rb, db/migrate/20191125145017_create_fields.rb, db/migrate/20191125145245_create_approvals.rb, db/migrate/20191125145638_create_user_specialties.rb, db/migrate/20191125145748_create_approval_fields.rb, db/migrate/20191125145820_create_user_fields.rb, db/schema.rb, test/models/approval_field_test.rb, test/models/approval_test.rb, test/models/clinic_test.rb, test/models/field_test.rb, test/models/specialty_test.rb, test/models/user_field_test.rb, test/models/user_specialty_test.rb
As described in the DB schema we defined : https://kitt.lewagon.com/products/4075
=> Generates models & migrations for DB schema

app/models/approval.rb, db/seeds.rb
basic seed file (update following), and one minor fix in approval model
=> add seed file with one user

app/models/approval.rb, db/seeds.rb
more users and approvals, bug fix in approval model
=> Seed update

app/policies/user_policy.rb
=> fixed policy bug

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tab_bar.scss, app/assets/stylesheets/pages/_show.scss, app/views/users/_profile_banner.html.erb, app/views/users/_profile_content.html.erb, app/views/users/_profile_interactive_tabs.html.erb, app/views/users/_profile_tabs.html.erb, db/seeds.rb, package.json, yarn.lock
Added styling to interactive tabs on doc profile page - feel free to reuse the CSS and HTML for the tabs.
=> Interactive tabs

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/pages/_show.scss, app/views/users/_profile-nav-btn-section.html.erb, app/views/users/_profile_approval_section.html.erb, app/views/users/_profile_banner.html.erb, app/views/users/_profile_content.html.erb, app/views/users/_profile_tabs.html.erb, app/views/users/show.html.erb
added profile layout updates, profile nav buttons and filter placeholders
=> Profile layout update

app/assets/stylesheets/pages/_show.scss, app/views/users/_profile-nav-btn-section.html.erb, app/views/users/_profile_approval_section.html.erb
=> minor styling update

app/models/user.rb, db/seeds.rb
some more doctors & clinics & reviews
=> adds a few more seeeeeeds

Gemfile, Gemfile.lock, app/models/clinic.rb, app/models/user.rb, app/uploaders/clinic_picture_uploader.rb, app/uploaders/profile_picture_uploader.rb, app/views/shared/_navbar.html.erb, app/views/users/_doctor_card.html.erb, app/views/users/_profile_banner.html.erb, app/views/users/_profile_interactive_tabs.html.erb, app/views/users/dashboard/_dashboard_reviews.html.erb
added Cloudinary & Carrierwave gem to project. Also, I replaced all image tags for users profile_picture & clinics clinic_picture in the views. Exchanged the default picture from doctor card in search, too.
=> Feature/cloudinary => Picture upload by user

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/pages/_show.scss, app/views/users/_profile_banner.html.erb, app/views/users/_profile_interactive_tabs.html.erb, app/views/users/_profile_tabs.html.erb, app/views/users/show.html.erb
basic refactoring of profile layout
=> refactor profile layout

app/controllers/users_controller.rb
Sharina and I fixed the issue of only being able to search when specified a location input. Now you can search with only one input specified
=> fixes issue to be only able to search with location

db/seeds.rb
I used a workaround, since I was not able to use the remote_photo_url. (I uploaded all needed pictures to cloudinary & used the cloudinary url )
=> adds cloudinary images to seed file

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_doctor_card.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_search_bar.scss, app/views/approvals/edit.html.erb, app/views/approvals/new.html.erb
spacing was too spacious. I reduced the spacing between filter bar & search-map-container.
=> adjusts spacing on search view

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
minor design updates on landing page
=> minor design updates

app/assets/stylesheets/pages/_dashboard.scss, app/views/users/dashboard/_dashboard_reviews.html.erb
=> minor updates

app/assets/stylesheets/components/_search_bar.scss, app/controllers/approvals_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_select2_sing_name.js, app/models/user.rb, app/views/approvals/_search_bar.html.erb, app/views/approvals/edit.html.erb, app/views/approvals/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/_doctor_card.html.erb, config/routes.rb
Based on the feedback received yesterday, I changed the flow of adding a recommendation.
1) In the Navbar `Search` and `Recommend` are now separated, when user is signed in.
2) I removed the `Add Recommendation`/ `Update Recommendation` button from the doctor card.
3) Changed routes for `new` and `create` approval actions (because we don't know the doc yet)
4) Added name search bar to new_approval view with select2
5) as soon as you select a doctor his doctor card is being displayed & the approval form appears
=> Flow improvement of adding an approval

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
=> new footer

db/seeds.rb
=> adds the bang to all create-methods to figure out the issue

db/seeds.rb
=> New seed update

db/seeds.rb
=> Ramiro info

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_search_bar.scss, app/javascript/components/set_active_class_to_field_choice.js
did it for all buttons & inputs
=> Removes default Chrome outline on click
